# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wil-playground
#   labels:
#     app: wil-playground
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: wil-playground
#   template:
#     metadata:
#       labels:
#         app: wil-playground
#     spec:
#       containers:
#         - name: playground
#           image: wil42/playground:v1
#           ports:
#             - containerPort: 8888


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: wil
#   labels:
#     app: wil-playground
# spec:
#   selector:
#     app: wil-playground
#   ports:
#     - port: 80
#       targetPort: 8888
#   type: ClusterIP















apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil
  namespace: dev
  labels:
    app: wil
spec:
  selector:
    matchLabels:
      app: wil
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
      - name: wil
        image: wil42/playground:v2
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: svc-wil
spec:
  selector:
    app: wil
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8888

# #https://kubernetes.io/docs/concepts/overview/working-with-objects/
# #https://www.loft.sh/blog/kubernetes-manifest
# #https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md
# #https://kubernetes.io/docs/reference/using-api/#:~:text=The%20version%20names%20contain%20beta,releases%20may%20introduce%20incompatible%20changes.