apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil_0
  namespace: dev
  labels:
    app: wil_1
spec:
  selector:
    matchLabels:
      app: wil_2
  template:
    metadata:
      labels:
        app: wil_3
    spec:
      containers:
      - name: wil
        image: wil42/playground:v1
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: svc-wil
spec:
  selector:
    app: wil
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8888

# #https://kubernetes.io/docs/concepts/overview/working-with-objects/
# #https://www.loft.sh/blog/kubernetes-manifest
# #https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md
# #https://kubernetes.io/docs/reference/using-api/#:~:text=The%20version%20names%20contain%20beta,releases%20may%20introduce%20incompatible%20changes.
