apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  labels:
    app: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - name: playground
          image: wil42/playground:v1
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  labels:
    app: playground
spec:
  selector:
    app: playground
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
  type: ClusterIP